"""add_ai_status_workflow_fixed

Revision ID: 2314b1fc27cf
Revises: 6a889f2b9020
Create Date: 2026-01-02 13:35:48.362258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2314b1fc27cf'
down_revision: Union[str, Sequence[str], None] = '6a889f2b9020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('ai_status', sa.String(length=20), nullable=True))
    op.add_column('scraped_data', sa.Column('ai_error_log', sa.Text(), nullable=True))
    op.create_index(op.f('ix_scraped_data_ai_status'), 'scraped_data', ['ai_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_data_ai_status'), table_name='scraped_data')
    op.drop_column('scraped_data', 'ai_error_log')
    op.drop_column('scraped_data', 'ai_status')
    # ### end Alembic commands ###
